# Site settings
title: intentional infusions
logo: /assets/images/infused_logo01.png
description: >
  Tea for your inadequency

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://intentional-infusions.io" # the base hostname & protocol for your site

# Syntax highlighting
highlightstyle: "railscasts"
styles: ["railscasts"]


# Handling Reading
exclude: ["README.md", "README.html", "Gemfile", "Gemfile.lock", "resources/*", "_drafts/*", "_mdwriter.cson"]

# Build settings
highlighter: null
markdown: kramdown

plugins:
  - jekyll-diagrams
  - jekyll-target-blank

jekyll-diagrams:
  font: "Hack Nerd Font"
  size: 320x240
  antialias: true

sass:
    sass_dir: _sass
